### ISSUE TITLE
 Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by nfantone** [frisb/highcharts-server#1]
Calling the `serve` method always end up with the following `TypeError` exception:

``` javascript
/home/nfantone/dev/js/my-project/node_modules/highcharts/lib/index.js:85
          return data += chunk.toString('utf8');
                              ^
TypeError: Cannot read property 'toString' of null
    at IncomingMessage.<anonymous> (/home/nfantone/dev/js/my-project/node_modules/highcharts/lib/index.js:85:31)
    at IncomingMessage.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at onEofChunk (_stream_readable.js:401:3)
    at readableAddChunk (_stream_readable.js:146:7)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnMessageComplete (_http_common.js:154:14)
    at Socket.socketOnEnd (_http_client.js:304:12)
    at Socket.emit (events.js:129:20)
```

This is due to the loop on the `reqCallback` anonymous function that reads _chunks_ of data from `res` but never checks if there are more bytes to be read, thus failing on the last iteration. It should be changed to something like:

``` javascript
        res.on('readable', function() {
          var chunk = res.read();
          return chunk ? data += chunk.toString('utf8') : data;
        });
```

That should make it.

**Comment by nfantone** [comment]
This is resolved by #3.

**Comment by liege** [comment]
Hello，when i run this example,The browser write :

```
Failed rendering: 
SyntaxError: Unable to parse JSON string
```

**Comment by ashbrener** [comment]
@liege what version are you running?

This issue was resolved in #3

**Comment by nfantone** [comment]
@liege Feel free to try https://github.com/nfantone/highcharts-export-server out. It might be useful to you.

**Comment by liege** [comment]
@nfantone 
run highcharts-export-server  `phantomjs lib/highcharts-convert.js -host 127.0.0.1 -port 3030`

```
Failed rendering: 
SyntaxError: JSON Parse error: Unexpected identifier "undefined"
```

**Comment by nfantone** [comment]
@liege That's an expected response if you don't provide any body to the request.

``` sh
→ curl http://localhost:3030
Failed rendering:
SyntaxError: JSON Parse error: Unexpected identifier "undefined"%
```

Please, follow [the documentation](https://github.com/nfantone/highcharts-export-server#api) for further examples. And you if have any other problems, post an issue [here](https://github.com/nfantone/highcharts-export-server/issues).
